apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: lightgbm-predictor
  namespace: kserve-graph-demo
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    model:
      modelFormat:
        name: lightgbm
      runtime: kserve-mlserver
      storageUri: pvc://model-pvc/lightgbm-predictor
